Fixed top and bottom borders sizing
CoolCodeFactory/BeautifulTextField pull request #5
Opened 2017-12-26 07:56 UTC by glebus

2017-12-26 08:18 UTC, cooler333 commented
@SviRiDoFFtr
@Yuop

2017-12-26 08:35 UTC, glebus commented
@SviRiDoFFtru
@Yuop

2017-12-27 14:14 UTC, Yuop requested changes

2017-12-27 14:14 UTC, Yuop commented on BeautifulTextField/Classes/BeautifulTextField.swift
> +    private func addConstraint(forBottomBorderView borderView: UIView) {
SnapKit!

2017-12-27 15:01 UTC, glebus commented on BeautifulTextField/Classes/BeautifulTextField.swift
> +    private func addConstraint(forBottomBorderView borderView: UIView) {
с ним было бы удобнее, но мне кажется что это оверхед - тянуть целую либу ради 2-3 констрейнов

2018-03-12 17:00 UTC, closed without merging